### ISSUE TITLE
rnpm link silently skips Xcode projects with "Example" or "Test" in the name

### ISSUE THREAD

**Issue by appden** [rnpm/rnpm#119]
The `GLOB_EXCLUDE_PATTERN` in `src/config/ios/findProject.js` makes these projects get ignored. I understand what the intention of it is, but the issue is if somebody creates a project called `MyTestApp` or `MyExampleApp` then `rnpm link` will silently skip updating the Xcode project. This can be overridden by explicitly listing the project path in `package.json`, but most users won't know to do that unless they have a specific need to.

Possible solutions:
- Make `ios/<project-name>.xcodeproj` the preferred first place to look, no matter what the name of the project is.
- If only one Xcode project is found, then just use that one regardless of its path
- Log a warning if the Xcode project was skipped due to its name (less good option IMHO)

**Comment by grabbou** [comment]
Hey,

That sounds reasonable. We could get a small perf. gain by first checking for `ios/project_name` (should solve 99% of `test`-like cases).

Also - if we fail to find any project - we could check if there are ANY .xcodeproj files in your folder and print a message `Hey, looks like you have some iOS stuff but we ignored it because it's likely it contains a keyword we blacklist. Check this link to see how to solve it`

What do you think?

**Comment by appden** [comment]
@grabbou That makes sense. It should only look for the canonical location (`ios/project.xcodeproj`) by default, and log a warning about how to point to it from your `package.json` for non-standard locations.

**Comment by grabbou** [comment]
@appden I just updated the content as you were answering - would you mind dbl checking?

**Comment by grabbou** [comment]
Re
> It should only look for the canonical location (ios/project.xcodeproj) by default, and log a warning about how to point to it from your package.json for non-standard locations.

I would still like to keep glob as described in my answer since I've seen dependencies I use that have .xcodeproj flat (in the root) instead of `ios`. It's also quite cheap to do and convenient in almost all cases, it's just we haven't added to much logging around that.

**Comment by appden** [comment]
@grabbou Thanks for the heads up on that! Your proposed solution would work, and probably would not break any backwards compatibility.

Now, if I weren't concerned about backwards compatibility, then I think I'd stand by my previous comment that `rnpm` should enforce React Native conventional locations (under `ios` and root for older projects) and require a `package.json` override to look somewhere else.

**Comment by grabbou** [comment]
Yeah, we've been discussing that in the past with @mkonicek and other FB guys that enforcing standards would be a cool idea! However, one of the main points I've came up with idea of rnpm was to make it work in my projects where react-native link wasn't able to follow paths etc. Since it's definitely easier to detect .xcodeproj `right` on iOS than to discover correct structure on android - I would say it's fine to keep it as is for now!

BTW -> maybe we should add a warning when app is not under `ios/abc.xcodeproj` saying that one is not following react-native structure and some of the features are likely to not work in the future?

**Comment by grabbou** [comment]
(There are also quite a few users integrating `react-native` into existing iOS apps. I would like to keep them in mind as well and that's the whole idea behind the config stuff)

**Comment by appden** [comment]
@grabbou Makes sense. I think if the Xcode project isn't under root or `ios`, then it would be good to give a warning that they should update `package.json` because it _might_ break in the future.

**Comment by grabbou** [comment]
That's however something we are going to support internally in React Native soon as rnpm is slowly moving its tools to core repository (cc: @Kureev), but we could print something like `other react-native commands might not work` (actually react-native run-ios recent version I think accepts a path to project, but upgrade won't even touch the stuff)

**Comment by appden** [comment]
Sorry if I misunderstood you. You're saying that `react-native` commands will all use the same logic to locate the Xcode project? That sounds like a good thing. :+1:

**Comment by grabbou** [comment]
Ultimately in the future - I think so! There's a relevant discussion about that in react native core contributors group on Facebook (I will link it in the morning since I have 3% of battery left :D )

**Comment by grabbou** [comment]
I have decided to implement

> Make ios/<project-name>.xcodeproj the preferred first place to look, no matter what the name of the project is.

in #120 and I think it will solve almost all cases for now.

**Comment by Kureev** [comment]
#120 has been merged. I believe we'll include it in the next release.

**Comment by grabbou** [comment]
Yeah, thanks! I can ship it tomorrow evening after few other small tweaks. Feel free to do it earlier

**Comment by appden** [comment]
@grabbou @Kureev thanks for addressing this issue!
