### ISSUE TITLE
How to copy images, videos into assets?

### ISSUE THREAD

**Issue by zhouhao27** [rnpm/rnpm#143]
I'd like to copy images, videos inside my **assets** folder into assets. How to do it ? 

```
  "rnpm": {
    "assets": ["assets"]
  }

```

This doesn't work.

**Comment by Kureev** [comment]
Can you name a library you're trying to link, please? These lines of code should be in the library itself, not in your project.

**Comment by grabbou** [comment]
True. 

There's no need to perform any extra actions in your project since you can do it manually.

However this is not the first request we receive and given it's super easy to implement (3 lines of code, iOS), I could consider doing that.

The importance of this feature might not be obvious if we think about things like images or videos, however I can see a point for automatically adding fonts to the project.

**Comment by zhouhao27** [comment]
It's a good feature to copy assets file automatically because there is no need to use Xcode or Android Studio anymore.

**Comment by Kureev** [comment]
@zhouhao27 sure, we do it automatically if library you're trying to link supports it. Otherwise there is no way to find which assets should be actually installed.

**Comment by grabbou** [comment]
...unless we support `assets` on a project level ;)

**Comment by Kureev** [comment]
@grabbou that means that all react-native modules should follow the same convention.

**Comment by grabbou** [comment]
Modules? We are talking about `projects` here - and as long as user can provide an array of assets in a config, I dont see any disadvantage here. This is mainly useful for automated fonts linking on iOS where it makes sense.

**Comment by Kureev** [comment]
You mean add functionality that allow users to link their non-modules code?

**Comment by grabbou** [comment]
As OP says - to link project assets (your project assets, not dependency assets).

**Comment by Kureev** [comment]
I'm not quite sure if that should be in the scope of rnpm-plugin-link. Probably, we need to have something standalone for this purpose.

**Comment by Secretmapper** [comment]
I think being able to link project level assets like these would be an awesome feature for rnpm as @zhouhao27 said it would remove the need to manually copy assets to the app IDEs.

However, isn't this what was fixed by https://github.com/rnpm/rnpm/pull/40 ? It seems that my fonts are being linked because of 40.

Assets other than fonts would be great too (though I'm not really sure why it doesn't seem to be supported - the commit doesn't. really check the file types from what I saw). For my specific use case, I need to be able to access the javascript file from the bundle, so being able to automatically include that would be awesome.

**Comment by grabbou** [comment]
@Secretmapper 

> Assets other than fonts would be great too

Generally `rnpm` just exposes assets and `link` plugin decides which types to handle (and we filter by type to get fonts there). Since on iOS you can handle all the other things by just requiring them and fonts seem to be a specific case, we didn't add anything extra yet. If you'll have another idea what else we can support here - please open an issue.

The OP issue seems to be already implemented as of #40. If it doesn't work (on latest `rnpm`) please let me know and reopen :)

**Comment by gnestor** [comment]
I have a single audio file (mute.caf) that needs to be copied into the project (via "Copy Bundle Resources") in order for my library to work properly. I tried including the audio file in the library group, adding it to the library's "Copy files" build phase, and adding the following the library's package.json:

```json
"rnpm": {
    "assets": ["mute.caf"]
  }
```

However, `rnpm link react-native-silent-switch` doesn't copy the audio file over...Am I missing something? 

To clarify: The mute.caf file is being used by the Objective C code and not React Native, otherwise `require()` would suffice.

**Comment by gnestor** [comment]
@grabbou @Kureev Is it possible to copy an audio file to a project's bundle using rnpm?

**Comment by grabbou** [comment]
Hey @gnestor, I think if your project uses it internally (your module) - you can just add it to the project by clicking `Add files to project` from the left Xcode sidebar (just like adding any other file) and then, add a Build Phase - Copy bundle resources inside your project manually. Is that not working?

Fonts are a special case because we need to add them to `Info.plist` as well.

**Comment by gnestor** [comment]
@grabbou Nice!

**Comment by grabbou** [comment]
PR submitted, waiting for @Kureev review. Tested with `mp3` file and all seems to be working well ;) Not sure about Android part, might need a follow up from Alexey (if you group by types - if you just copy, then it's probably fine).

Feel free to ship it right after, I'll be offline for the 2nd part of the day

**Comment by gnestor** [comment]
I tested my use case wit the most recent version of rnpm but it's still not copying the file listed in package.json to my Xcode project. 

package.json
```js
"rnpm": {
    "assets": [
      "mute.caf"
    ]
  }

```

I'm expecting mute.caf to be copied to my bundle ("Copy Bundle Resources").
