### ISSUE TITLE
Copy all assets (not just fonts) ?

### ISSUE THREAD

**Issue by jdeniau** [rnpm/rnpm#160]
Hi,

I just discovered the `assets` possibility, but it seems that it only copy fonts assets.

Why did it not copy other assets types (images, sounds, etc.) ? Is there something I did not understand ? 

Thank you

**Comment by grabbou** [comment]
Hey,

Well, you don't need to copy other assets types since you can just require them with the standard syntax, so there's no need to do anything extra.

The `copyAssets` part of `rnpm` is intended to handle special cases, like fonts (in fact, we only copy them on Android since on iOS, there's no need and we can just reference them from another location).

**Comment by jdeniau** [comment]
Ok, my problem was for launchscreen and stuff like that on ios, but I will investigate further on how to use assets that are not present in Xcode project to do so.

Thank you !

**Comment by grabbou** [comment]
Awesome :) good luck!
