### ISSUE TITLE
[iOS] Duplicate symbols issue

### ISSUE THREAD

**Issue by aksonov** [rnpm/rnpm#180]
When I use several native iOS modules (react-native-tcp & react-native-xmpp) that use the same obj-c library (CGDAsyncSocket), i'm getting this error. How to avoid that?

**Comment by zkenes** [comment]
I've met the same issue, but in my case it was `react-native-maps`. Did you solve your trouble?

**Comment by aksonov** [comment]
@zkenes no. it is pity that issues are not monitored here..

**Comment by zkenes** [comment]
@aksonov Have you tried to add manually?

**Comment by aksonov** [comment]
I've forked and then dep from one of native iOS module. It solved issue but it definitely looks like a hack (and using 'forked' module)

**Comment by grabbou** [comment]
Well, we can't do anything about that since as far as I am aware, the library (Cocoa Async Socket) is added manually to the dependency `xcodeproj` and `rnpm` has nothing to do here. The developer or maintainer of these projects should be notified of the issue and ideally asked to leave adding that library up to users.

**Comment by aksonov** [comment]
@grabbou I'm maintainer of react-native-xmpp and it looks strange to require users to install Cocoa Async Socket manually - they are using rnpm and expect not to add manually anything, especially to third-party modules, right? Is there any workaround? Or CocoaPods is only solution (i thought rnpm is better alternative to CocoaPods designed for React Native)
