### ISSUE TITLE
Explain difference with `rem`

### ISSUE THREAD

**Issue by tonyxiao** [rnpm/rnpm#25]
There's another effort here https://github.com/exponentjs/rem

Could you explain your thinking behind `rnpm` and how it's different from `rem`?

**Comment by grabbou** [comment]
Hey! Sure ;)

In my opinion rem is more similar to `rnpm-plugin-link` than to `rnpm` itself.

According to their documentation, it operates on top of `Cocoapods` - that is, when you add it to your project, it sets up Cocoapods project for iOS behind the scenes (that means you have `xcworkspace` created). Then, it uses local pod specs from 3rd party modules to link them automatically to your project. And since that's beneficial in most cases - it's not widely supported by the community at this point and it's not clear what's the direction everyone's going to go with. It also requires a few steps to be taken by developers (https://github.com/exponentjs/rem#writing-modules-for-rem-for-module-authors) meaning that the number of packages it supports is limited and depends on the community effort.

We have took slightly different approach with `rnpm-plugin-link` - instead of using Cocoapods, it just follows the standard way of working with dependencies as described in React Native docs. That is - we just add `xcodeproj` to your `Libraries` folder, link static libraries (e.g. libReact.a) and such. We also detect fonts and other assets 3rd party modules can export. It's more like an automation tool that just repeats the steps you would've usually taken. Thanks to that, we were able to fully automate that process and `assume` quite a few things about the project and its dependencies. That means - in almost all cases (we are trying to cover them all, issues welcome if something does not work) there should be no extra work needed - all should just work.

One of the biggest advantages in my opinion is also that we support the same set of features on Android straight away.

The long-term goal for `rnpm` itself is to support wider set of features by e.g. allowing you to publish your app to AppStore directly from command line without worrying about the details and certificates (see for example `fastlane` project).

Hope that helps, but since it's quite late and I wanted to get back to you as soon as possible, feel free to ask for more specific bits as well :)

**Comment by grabbou** [comment]
PS. Thanks to the plugin system, one can create `rnpm-plugin-link-buck` that will work in the same manner but use `buck` internally.

**Comment by tonyxiao** [comment]
Hey @grabbou thanks so much for the clarification. What if the native modules themselves have other native dependencies? One of the things cocoapods does is resolving duplicate dependencies and make sure they are only linked into the project once. (and compatible versions are used).

**Comment by grabbou** [comment]
Yes, that's the feature I like in Cocoa. We might use it at some point to handle non npm modules and native frameworks npm modules depend on.

For now, I think it has to be done manually (eg copy paste or add system frameworks). Ideas are welcome! 

For system frameworks - I think simple array of their names would be efficient since there's no download required.

**Comment by tonyxiao** [comment]
Got it. Have you considered using Carthage instead? it takes care of dependency resolution but is unopinionated about exactly how those dependencies get integrated into the xcodeproj, seems to be a nice complement to the way rnpm works (and does not require any extra effort on module author's part).

**Comment by Kureev** [comment]
I'd like to have a @grabbou opinion on it, but I'd say it should be a second-wave improvement

**Comment by grabbou** [comment]
Yes, I've been using it internally and so far it's been working quite well. We might use it at some point programatically but it's more like an idea for a plugin that could outperform our standard `rnpm-plugin-link` at some point. 

For now, we wanted to get aligned with the standard process, but I agree that this kind of stuff will have to be addressed at some point soon before we move on.

**Comment by Kureev** [comment]
Can you move this proposal to the separated issue? In this case we would be able to close this one and mark yours as a "potential feature"?

**Comment by grabbou** [comment]
I'd move that to `rnpm-plugin-link` since it's more like an improvement for link itself.

**Comment by tonyxiao** [comment]
Done, feel free to close this.
