### ISSUE TITLE
Deep integration into react-native

### ISSUE THREAD

**Issue by Kureev** [rnpm/rnpm#92]
- [x] Discuss replacing `react-native`'s `underscore` by `lodash`
- [x] Remove unused `rnpm` dependencies
- [x] Scope an `rnpm` test coverage by CI
- [x] Clarify the next step using `update-notifier`
- [x] Discuss using `fs-extra` (replacing by something else?)
- [x] Discuss using `glob`
- [x] Discuss using `commander` (replace current react-native implementation?)

**Comment by grabbou** [comment]
I think glob is fine and there's no alternative to it.

Re: `commander` - I'd remove it and use react-native specific implementation (following what @mkonicek said recently). I'll submit a PR with that today by the evening.

**Comment by Kureev** [comment]
`commander` - compose a PR and let's discuss it. I also feel the same about it
`update-notifier` - I agree to remove it, but we need to discuss how we're going to maintain versions in the future
`lodash` - I've took a look on RN core and I'd prefer to move RN to `lodash` than us to move to `underscore`. Hope we can negotiate it.
`fs-extra` - we use it for the copying. I feel we can replace them by a hand-written code.

**Comment by grabbou** [comment]
`I'd prefer to move RN to lodash` - RN is 3810231x bigger and there's no point in introducing potential issues (in some cases these are not drop in replacements). Also, I'd imagine that's something Facebook is using internally, so -1 from me #reality

Re: fs-extra, do it for link anyway!

Re: versions - easy, new version shipped every 2 week (since CLI always ships at the time RN ships) and the same rc process.

**Comment by Kureev** [comment]
About lodash vs underscore: https://github.com/facebook/react-native/search?l=javascript&q=underscore&utf8=%E2%9C%93

**Comment by Kureev** [comment]
I think we discussed all these points and I can close this issue
